Add encoding methods
Esri/arcgis-html-sanitizer pull request #86
Opened 2022-03-04 20:04 UTC by BlakeStearman

### Changes

**feat: Add `encodeHTMLEntities` and `encodeAttrValue` methods.**

The `encodeHTMLEntities` method encodes a defined set of characters found in HTML strings to their hexadecimal HTML entity code. The set of character mappings follows:

* `&` &rarr; `&#x38;`
* `<` &rarr; `&#x3C;`
* `>` &rarr; `&#x3E;`
* `"` &rarr; `&#x22;`
* `'` &rarr; `&#x27;`
* `/` &rarr; `&#x2F;`

The `encodeAttrValue` method is for encoding strings meant for use as HTML tag attribute values. It encodes all non-alphanumeric ASCII values to their hexadecimal HTML entity code, e.g., `&x#HH;` where `HH` is the hexadecimal value.

2022-03-04 21:50 UTC, dasa requested changes

2022-03-04 21:50 UTC, dasa commented on src/index.ts
> +    return String(value).replace(/[\x00-\x7F]/g, (c, idx) => {
Should `\x7F` be `\xFF` to go up to 255?

2022-03-04 21:50 UTC, dasa commented on src/index.ts
> +  public encodeHTMLEntities(value: string): string {
Would `encodeHTML` be a better name since this doesn't encode entities in the `value` parameter?

2022-03-04 21:50 UTC, dasa commented on README.md
> +#### Encode Attribute Values
This doc should probably better clarify the use case for this vs. `sanitizeHTMLAttribute`.

2022-03-04 21:50 UTC, BlakeStearman commented on src/index.ts
> +    return String(value).replace(/[\x00-\x7F]/g, (c, idx) => {
Will correct that, good catch.

2022-03-04 21:58 UTC, BlakeStearman commented on src/index.ts
> +  public encodeHTMLEntities(value: string): string {
I agree that `encodeHTML` is a better name for it.

2022-03-04 22:11 UTC, BlakeStearman commented on README.md
> +#### Encode Attribute Values
Will work on this one as well.

2022-03-04 22:33 UTC, BlakeStearman commented
@dasa I've made the following updates:
* Fix the ASCII ending range in the regex for `encodeAttrValue`.
* Change the method name of `encodeHTMLEntities` to `encodeHTML`, updated readme and tests to reflect this.
* Applied clarification in the readme for `encodeHTML` and `encodeAttrValue` as to how they differ from the `sanitize` and `sanitizeHTMLAttribute` methods, respectively.

2022-03-04 23:20 UTC, dasa approved these changes
👍🏻

2022-03-07 20:23 UTC, gbrown-gis commented
Thank you for working on this.  Please attach test results for each of the methods.

2022-03-10 21:48 UTC, ssylvia approved these changes

2022-03-10 21:48 UTC, ssylvia commented on src/index.ts
> +        // @ts-ignore safeAttrValue does handle undefined cssFilter
```suggestion
        // @ts-expect-error safeAttrValue does handle undefined cssFilter
```

2022-03-21 16:24 UTC, BlakeStearman commented
@gbrown-gis The tests are here:
https://github.com/Esri/arcgis-html-sanitizer/pull/86/files#diff-258035e5968f6bf645400d417f310218d7d9a9a10606a3c34e7f55db193f58f3R507-R526
```typescript
  test("encodes HTML", () => {
    const sanitizer = new Sanitizer();
    const html = `<a href="https://someurl.tld">Link '1'</a> &middot; <a href="https://someurl.tld/path1">Link '2'</a>`;
    const encoded = `&#x3C;a href=&#x22;https:&#x2F;&#x2F;someurl.tld&#x22;&#x3E;Link &#x27;1&#x27;&#x3C;&#x2F;a&#x3E; &#x38;middot; &#x3C;a href=&#x22;https:&#x2F;&#x2F;someurl.tld&#x2F;path1&#x22;&#x3E;Link &#x27;2&#x27;&#x3C;&#x2F;a&#x3E;`;
    const text = "This is plain text with no encoding necessary.";
    expect(sanitizer.encodeHTML(html)).toBe(encoded);
    expect(sanitizer.encodeHTML(text)).toBe(text);
  });

  test("encodes HTML attribute values", () => {
    const sanitizer = new Sanitizer();
    const url = "https://someurl.tld/path1?f=json&ts=123002398483";
    const alert = "javascript:alert(document.cookie)";
    const encodedUrl =
      "https&#x3a;&#x2f;&#x2f;someurl&#x2e;tld&#x2f;path1&#x3f;f&#x3d;json&#x26;ts&#x3d;123002398483";
    const encodedAlert =
      "javascript&#x3a;alert&#x28;document&#x2e;cookie&#x29;";
    expect(sanitizer.encodeAttrValue(url)).toBe(encodedUrl);
    expect(sanitizer.encodeAttrValue(alert)).toBe(encodedAlert);
  });
```
<img width="654" alt="Screen Shot 2022-03-21 at 9 20 37 AM" src="https://user-images.githubusercontent.com/5124840/159305446-9088a0a0-46b1-459b-b91f-f6e8969a78b7.png">

Current tests ensure 100% code coverage, but initial tests I put in are not exhaustive. Looking for feedback on additional tests you want to see or are required for these methods.

2022-04-15 20:52 UTC, BlakeStearman commented
@ssylvia @dasa Sorry for the long delay on this one. I've expanded the tests to cover all encoded characters for the `encodeHTML` and `encodeAttrValue` methods. Please review as you have time.

2022-04-18 14:15 UTC, ssylvia approved these changes

2022-04-18 16:25 UTC, dasa submitted a review, later dismissed
👍🏻

2022-04-19 23:22 UTC, gbrown-gis commented
Hi Team, thank you for working on this.    Reviewed that test for encodeAttrValues and  found that the testing appears to be missing for " (double quote) and ' (single quote).  

<img width="478" alt="image" src="https://user-images.githubusercontent.com/37595904/164116957-6dff1faf-b8be-4789-8482-3b589ec52e52.png">

2022-04-19 23:27 UTC, BlakeStearman commented
@gbrown-gis Thanks, will update that.

2022-04-20 00:00 UTC, BlakeStearman commented
@gbrown-gis I've added explicit tests for the `"` and `'` characters in `encodeAttrValues`. That said, they were already being tested in the loop when `charCode` is 34 and 39, respectively. I think the explicit tests help clarify it either way.

2022-04-20 15:44 UTC, dasa approved these changes

2022-04-20 15:51 UTC, ssylvia approved these changes

2022-04-21 20:29 UTC, gbrown-gis approved these changes
Thanks for adding.
    // Ensure " and ' are encoded correctly
     expect(sanitizer.encodeAttrValue('"')).toBe("&#x22;");
     expect(sanitizer.encodeAttrValue("'")).toBe("&#x27;");

2022-04-25 19:09 UTC, merged