Remove dependency on lodash.isplainobject
Esri/arcgis-html-sanitizer pull request #90
Opened 2022-08-19 19:12 UTC by BlakeStearman

### Changes
* feat: Remove dependency on lodash._isPlainObject.

  Adds local implementation of `isPlainObject` as well as unit tests.

2022-08-19 19:52 UTC, dasa requested changes

2022-08-19 19:52 UTC, dasa commented on src/plainObject.ts
> +"use strict";
Remove

2022-08-19 19:54 UTC, dasa commented
Can the Node 10 and 12 tests be removed since those versions are no longer [maintained](https://github.com/nodejs/Release/#end-of-life-releases)?

2022-08-19 19:55 UTC, dasa approved these changes

2022-08-19 19:55 UTC, dasa commented on src/plainObject.test.ts
> +// import ldIsPlainObject from "lodash.isplainobject";
Remove line

2022-08-19 19:56 UTC, dasa commented
It'd be good to add Node 18 to the tests.

2022-08-19 20:02 UTC, dasa approved these changes

2022-08-19 20:13 UTC, dasa approved these changes
👍🏻

2022-08-19 22:31 UTC, gbrown-gis approved these changes
Verified that library is removed and replaced with our own file implementation.

2022-08-22 12:30 UTC, ssylvia approved these changes

2022-08-22 12:31 UTC, merged