feat: allow customizing css filter and establish modified defaults
Esri/arcgis-html-sanitizer pull request #97
Opened 2024-05-03 20:59 UTC by BlakeStearman

Sets the default CSS filter to turn on `overflow`, `line-height` and the flexbox options: `flex, `flex-basis`, `flex-direction`flex-flow`, `flex-grow`, `flex-shrink`, `flex-wrap`.

Added tests to ensure that extending defaults and overriding work as intended, as well as to test out the CSS properties enabled by default.

2024-05-03 21:05 UTC, dasa approved these changes
👍🏻

2024-05-03 21:05 UTC, dasa commented on src/index.ts
> +
delete NL

2024-05-06 16:53 UTC, dasa submitted a review, later dismissed
👍🏻

2024-05-07 14:19 UTC, ssylvia requested changes

2024-05-07 14:19 UTC, ssylvia commented on src/index.ts
> +  private readonly arcgisCSSWhiteListOverrides: ICSSWhiteList = {
It would be worth exposing a `private readonly arcgisCSSWhiteList: ICSSWhiteList` for developers who want the original to extend the CSS whitelist only but want to override the tag list.

2024-05-07 14:19 UTC, ssylvia commented on src/index.ts
> +    Object.keys(this.arcgisCSSWhiteListOverrides).forEach((key) => {
Since `xss.getDefaultCSSWhiteList` and `this.arcgisCSSWhiteListOverrides` are read-only, how about calling this only once at the top of the module and then exposing it as the public `CSSWhitelist` variable:

2024-05-07 16:53 UTC, BlakeStearman commented
@ssylvia Thanks for the great suggestions. I've exposed the ArcGIS defaults as `arcgisCSSWhiteList`, and streamlined how it's created, which should make the code cleaner and easier to follow. I've also added a test for the public css whitelist property. Please let me know if you see any other areas that should be udpated.

2024-05-07 16:54 UTC, ssylvia approved these changes

2024-05-07 16:57 UTC, merged